**Load CSV, Excel and Parquet Files**

Load three common dataset formats used in Machine Learning:

- CSV files

- Excel files

- Parquet files

In [ ]:
# install the required libraries
%pip install -q pandas openpyxl pyarrow
# restart the kernel to use the updated packages

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1]:
import os
import pandas as pd

**1. Load the csv file**

In [2]:
df_csv = pd.read_csv("titanic.csv")

In [3]:
type(df_csv)

pandas.core.frame.DataFrame

In [4]:
df_csv.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
df_csv.shape

(891, 12)

In [6]:
# pd.read_csv?

In [7]:
# load selected columns
df_csv_subset = pd.read_csv(
    filepath_or_buffer="titanic.csv",
    usecols=["Survived", "Pclass", "Age", "Fare"]
)

In [8]:
df_csv_subset.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [10]:
df_csv_subset.shape

(891, 4)

In [11]:
# Load first N rows
df_csv_preview = pd.read_csv("titanic.csv", nrows=5)

In [12]:
df_csv_preview.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [13]:
df_csv_preview.shape

(5, 12)

**2. Load the Excel file**

In [14]:
df_excel = pd.read_excel("titanic.xlsx")

In [15]:
df_excel.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [18]:
# load selected columns
df_excel_subset = pd.read_excel(
    io="titanic.xlsx",
    usecols=["Survived", "Pclass", "Age", "Fare"]
)

In [19]:
# pd.read_excel?

In [21]:
df_excel_subset.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [22]:
# check sheet names
xls = pd.ExcelFile("titanic.xlsx")
print(xls.sheet_names)

['Sheet1']

In [23]:
df_excel_sheet = pd.read_excel("titanic.xlsx", sheet_name="Sheet1")

In [24]:
df_excel_sheet.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**3. Load the Parquet file**

In [25]:
df_parquet = pd.read_parquet("titanic.parquet")
df_parquet.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S

In [26]:
# Load selected columns from Parquet
df_parquet_subset = pd.read_parquet(
    "titanic.parquet",
    columns=["Survived", "Pclass", "Age", "Fare"]
)
df_parquet_subset.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

**4. Load the csv file with different separator**

In [27]:
df_tab = pd.read_csv("titanic_tab.csv", sep="\t")
df_tab.shape

(891, 12)

**5. Compare file sizes**

In [28]:
def file_size(path):
    size_bytes = os.path.getsize(path)
    size_kb = round(size_bytes / 1024, 2)
    size_mb = round(size_bytes / (1024 * 1024), 4)
    return size_kb, size_mb

for f in ["titanic.csv", "titanic.xlsx", "titanic.parquet", "titanic_tab.csv"]:
    kb, mb = file_size(f)
    print(f"{f}: {kb} KB  |  {mb} MB")

titanic.csv: 58.89 KB  |  0.0575 MB
titanic.xlsx: 67.22 KB  |  0.0656 MB
titanic.parquet: 40.43 KB  |  0.0395 MB
titanic_tab.csv: 58.91 KB  |  0.0575 MB